version: '3'
services:
  mariadb:
    build:
      context: ./mariadb
    ports:
      - "3306:3306"
    volumes:
      - volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password_database
  python:
    build:
      context: ./python
    depends_on:
      - mariadb

