version: '3'
services:
  mariadb:
    image: 'mariadb:latest'
    container_name: 'mariadb_p_bot'
    restart: always
    environment:
      MYSQL_USER: 'jc'
      MYSQL_PASSWORD: 'password_database'
      MYSQL_DATABASE: 'discord_p'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
        - ./volume/:/var/lib/mysql/
    networks:
      - intern
  python:
    build:
      context: ./python
    depends_on:
      - mariadb
    networks:
      - intern
networks:
  intern: